name: multimodal-simulation
channels:
  - conda-forge
  - aihabitat
dependencies:
  - python=3.9
  - habitat-sim=0.3.3
  - withbullet
  - opencv
  - ffmpeg
  - imageio
  - imageio-ffmpeg
  - numpy=1.26.4
  - scipy=1.13.1
  - trimesh=4.7.4
  - pillow
  - pip
