name: multimodal-pick-and-place
channels:
  - conda-forge
  - aihabitat
dependencies:
  - python=3.9
  - habitat-sim=0.3.3
  - withbullet
  - opencv
  - ffmpeg
  - imageio
  - imageio-ffmpeg
  - numpy=1.26.4
  - scipy=1.13.1
  - trimesh=4.7.4
  - pillow
  - pip
  - pip:
      - dora-rs==0.5.0
      - dora-rs-cli==0.5.0
      - pyarrow==21.0.0
